### ISSUE TITLE
integration within lite-xl

### ISSUE THREAD

**Issue by franko** [takase1121/lite-nagbar#3]
I have recently noticed you completed the plugin.

It is really a nice work and I have seen you found a smart solution to plug the nagbar into the node tree at the right position, well done.

I would like to integrate this plugin directly within lite-xl. Are you interested in contributing a PR ? I guess the only work required is to plug the nagbar view directly from core/init.lua and move it in the core directory.

**Comment by takase1121** [comment]
The plugging mechanism would be much easier if it was directly integrated to `core/init.lua` since I've got access to everything I need without hacks. I will try.
